In [51]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [52]:
titanic = pd.read_excel(r"C:\Users\dell\Downloads\titanic_df.xls",index_col=0)

In [53]:
titanic.shape

(891, 11)

In [54]:
titanic.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [55]:
titanic = titanic[['Name','Pclass','Sex','Age','Survived']]
print(titanic.shape)

(891, 5)


In [56]:
titanic.describe(include='all')

Name      Pclass   Sex         Age    Survived
count                       891  891.000000   891  714.000000  891.000000
unique                      891         NaN     2         NaN         NaN
top     Braund, Mr. Owen Harris         NaN  male         NaN         NaN
freq                          1         NaN   577         NaN         NaN
mean                        NaN    2.308642   NaN   29.699118    0.383838
std                         NaN    0.836071   NaN   14.526497    0.486592
min                         NaN    1.000000   NaN    0.420000    0.000000
25%                         NaN    2.000000   NaN   20.125000    0.000000
50%                         NaN    3.000000   NaN   28.000000    0.000000
75%                         NaN    3.000000   NaN   38.000000    1.000000
max                         NaN    3.000000   NaN   80.000000    1.000000

In [57]:
titanic.isnull().sum()

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64

In [58]:
##imputing the missing data with mean value
titanic['Age'].fillna(int(titanic['Age'].mean()),inplace=True)
print(titanic.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


#       transforming the categoricsl data to numerical data

In [59]:
from sklearn import preprocessing
colname=['Sex']
le=preprocessing.LabelEncoder()
for x in colname:
    titanic[x]=le.fit_transform(titanic[x])
    

In [60]:
print(titanic.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  


In [61]:
##creating X and Y
X_train=titanic.values[0:870,1:-1]
Y_train=titanic.values[0:870,-1]
Y_train=Y_train.astype(int)

X_test=titanic.values[870:891,1:-1]
Y_test=titanic.values[870:891,-1]
Y_test=Y_test.astype(int)

                 

In [62]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(870, 3)
(870,)
(21, 3)
(21,)


In [63]:
#skleaning data to bring it into range
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

scaler.fit(X_train)
#scaler.fittransform(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)




In [64]:
X_train

array([[ 0.82810204,  0.73472649, -0.5784206 ],
       [-1.56541549, -1.3610507 ,  0.64650051],
       [ 0.82810204, -1.3610507 , -0.27219032],
       ...,
       [-1.56541549,  0.73472649,  0.11059753],
       [ 0.82810204,  0.73472649, -0.04251761],
       [ 0.82810204,  0.73472649, -1.95645684]])

# PREDICTING THE MODEL BASED ON KNN

In [65]:
## predicitng using the Kneighbors_lCassifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')

# euclidean,minkowsi,manhattan

model_KNN.fit(X_train,Y_train)
Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0)]


In [66]:
#classification problems

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('classification report:',)
print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('accuracy of the model:',acc)

[[13  1]
 [ 2  5]]
classification report:
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        14
           1       0.83      0.71      0.77         7

    accuracy                           0.86        21
   macro avg       0.85      0.82      0.83        21
weighted avg       0.86      0.86      0.85        21

accuracy of the model: 0.8571428571428571


# PREDICTING MODEL ON EXTERNAL DATA

In [67]:
row= {'Pclass':3,
     'Sex': 1,
     'Age':50}

#Convert it into a dataframe
test_data =pd.DataFrame(data = row,index=[0])
test_data

Pclass  Sex  Age
0       3    1   50

In [68]:
test_data=scaler.transform(test_data)
test_data

array([[0.82810204, 0.73472649, 1.56519135]])

In [69]:
Y_pred_temp=model_KNN.predict(test_data)
Y_pred_temp

array([0])


# WORKING ON VALUE K

In [70]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN=KNeighborsClassifier(n_neighbors=K,metric='euclidean')
    
    model_KNN.fit(X_train,Y_train)
    Y_pred= model_KNN.predict(X_test)
    print('Accuracy is ',accuracy_score(Y_test,Y_pred),'for k-value',K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)
  

Accuracy is  0.7619047619047619 for k-value 1
Accuracy is  0.8095238095238095 for k-value 2
Accuracy is  0.8095238095238095 for k-value 3
Accuracy is  0.8571428571428571 for k-value 4
Accuracy is  0.8571428571428571 for k-value 5
Accuracy is  0.8095238095238095 for k-value 6
Accuracy is  0.8095238095238095 for k-value 7
Accuracy is  0.8571428571428571 for k-value 8
Accuracy is  0.8095238095238095 for k-value 9
Accuracy is  0.9047619047619048 for k-value 10
Accuracy is  0.8571428571428571 for k-value 11
Accuracy is  0.9047619047619048 for k-value 12
Accuracy is  0.9047619047619048 for k-value 13
Accuracy is  0.8571428571428571 for k-value 14
Accuracy is  0.9047619047619048 for k-value 15
Accuracy is  0.8571428571428571 for k-value 16
Accuracy is  0.8571428571428571 for k-value 17
Accuracy is  0.8095238095238095 for k-value 18
Accuracy is  0.8571428571428571 for k-value 19
Accuracy is  0.8095238095238095 for k-value 20
Accuracy is  0.8095238095238095 for k-value 21
Accuracy is  0.8571428

In [71]:
my_dict

{1: 0.7619047619047619,
 2: 0.8095238095238095,
 3: 0.8095238095238095,
 4: 0.8571428571428571,
 5: 0.8571428571428571,
 6: 0.8095238095238095,
 7: 0.8095238095238095,
 8: 0.8571428571428571,
 9: 0.8095238095238095,
 10: 0.9047619047619048,
 11: 0.8571428571428571,
 12: 0.9047619047619048,
 13: 0.9047619047619048,
 14: 0.8571428571428571,
 15: 0.9047619047619048,
 16: 0.8571428571428571,
 17: 0.8571428571428571,
 18: 0.8095238095238095,
 19: 0.8571428571428571,
 20: 0.8095238095238095,
 21: 0.8095238095238095,
 22: 0.8571428571428571,
 23: 0.8095238095238095,
 24: 0.8095238095238095,
 25: 0.8095238095238095,
 26: 0.8571428571428571,
 27: 0.8571428571428571,
 28: 0.8571428571428571,
 29: 0.8571428571428571,
 30: 0.8571428571428571}

In [74]:
for K in my_dict:
    if my_dict[K]==max(my_dict.values()):
        print(K,':',my_dict[K])

10 : 0.9047619047619048
12 : 0.9047619047619048
13 : 0.9047619047619048
15 : 0.9047619047619048


In [75]:
## predicitng using the Kneighbors_lCassifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=10,
                              metric='euclidean')

# euclidean,minkowsi,manhattan

model_KNN.fit(X_train,Y_train)
Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('classification report:',)
print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('accuracy of the model:',acc)

[[12  2]
 [ 0  7]]
classification report:
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model: 0.9047619047619048


In [79]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=13,
                              metric='euclidean')

# euclidean,minkowsi,manhattan

model_KNN.fit(X_train,Y_train)
Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print('classification report:',)
print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print('accuracy of the model:',acc)

[[12  2]
 [ 0  7]]
classification report:
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model: 0.9047619047619048
